name: sprouty_app
description: SPROUTY app
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/SPROUTY_SF.png
    - assets/google.svg
    - assets/species/espatifilo.png
    - assets/species/lengua_de_suegra.png
    - assets/species/monstera.png
    - assets/species/poto.png
    - assets/species/suculenta.png

  
